name: fitdaily
description: "A daily exercise app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  toggle_switch: ^2.3.0
  read_more_text: ^0.0.5
  video_player: ^2.2.16
  flexivideoplayer: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

